-- 코드를 작성해주세요
# SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
# FROM DEVELOPERS d
# INNER JOIN SKILLCODES s ON d.SKILL_CODE & s.CODE > 0
# WHERE s.CATEGORY = 'Front End'
# ORDER BY d.ID ASC;















# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM SKILLCODES s INNER JOIN
# DEVELOPERS d ON s.CODE & d.SKILL_CODE > 0
# WHERE s.CATEGORY = 'Front End'
# ORDER BY ID ASC
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S
ON D.SKILL_CODE & S.CODE = S.CODE
WHERE S.CATEGORY = 'Front End'
ORDER BY D.ID